### ISSUE TITLE
Bug: Crash with segmentation fault

### ISSUE THREAD

**Issue by NGC935** [Wunderfitz/harbour-piepmatz#105] opened 2021-04-02 12:14 UTC
Hi, this is the first time I have a problem with piepmatz, thanks for this stable software.

## What happened

I was scrolling through my timeline suddenly piepmatz crashes. I was reproducable, every time I opened this app and scrolled to the same tweet. I never saw that tweet since the Twitter website never showed it to me.

## Debugging

I used the CLI to open piepmatz and saved the output to a textfile. The last lines of the log are here:

```
[D] unknown:0 - TwitterApi::getOpenGraph "https://www.reddit.com/r/Strava/comments/mhocho/strava_to_be_acquired_by_google_whats_happens_next/"
[D] unknown:0 - TwitterApi::handleGetOpenGraphFinished
[D] unknown:0 - Open Graph content type header:  "text/html; charset=UTF-8"
[D] unknown:0 - Available Open Graph charset:  "UTF-8"
[D] unknown:0 - Open Graph Charset for  "https://hubs.li/H0KkZSh0" :  "UTF-8"
[W] unknown:310 - file:///usr/share/harbour-piepmatz/qml/components/TweetElement.qml:310:29: QML Image: Error transferring https://preview.redd.it/kpleg3iyaec51.jpg?overlay-align=bottom,left&amp;crop=900:471.204188482,smart&amp;overlay-height=15p&amp;overlay=/watermark/t5_2tex6.png%3Fs%3Dd11d1316e35e697280b509f23c1fb09a0240783c&amp;width=900&amp;height=471.204188482&amp;auto=webp&amp;s=baf4140166a841912129f7b964c1d6eabd82ea76 - server replied: Forbidden
[D] unknown:0 - TwitterApi::getOpenGraph "https://meet.jit.cloud/20JahreRadioTux"
Segmentation fault (core dumped)
```

if you need the full log, I'll send you the whole file.

thanks!

**Comment by Wunderfitz** [comment] 2021-04-05 09:03
Thanks, that should already help to find the root cause...

**Comment by Wunderfitz** [comment] 2021-04-05 10:15
Seems that jit.cloud is closing the connection prematurely that causes that segmentation fault somehow. I haven't found any real solution yet. A small debugging showed that I can't handle this (yet) in my code, so I simply don't try to get the URL descriptions for this domain for the time being...

That's the behavior when invoking the URL from Postman - might be the same when doing it from the Qt client:
```
Client network socket disconnected before secure TLS connection was established
```

**Closed** 2021-04-05 10:20 UTC
Labels: bug
